### PR TITLE
Add useStoreKitIfAvailable switch

### PR DESCRIPTION
**Pull request by hyouuu**
So app can choose whether they want to use StoreKit or not. BTW currently the storeKit is not submittable when I tried it.

### CODE REVIEW

**Comment by takecian** [comment]
@hyouuu , thank you for sending PR. BTW I think StoreKit is available for submitting app to AppStore. Did you get error when submitting apps including StoreKit?

**Comment by hyouuu** [comment]
I couldn't try it in production as it's too risky, but either way giving people a choice is better than none?

**Comment by takecian** [comment]
I'm not sure why developers want to avoid using StoreKit, why do you think using StoreKit is risky?

**Comment by hyouuu** [comment]
Because different UIs are arguably better or worse; I'm not saying using StoreKit is risky, but that in debug mode it doesn't work, and I can't put it in App Store version to try out whether it works in production

**Comment by hyouuu** [comment]
Thanks!

**Comment by takecian** [comment]
I've released with your PR as [0.1.5](https://github.com/takecian/SwiftRater/releases/tag/0.1.5).
Thank you!

**Pull request merged**
