### PR TITLE
node is produced by multiple commands

### PR DESCRIPTION
**Pull request by krezzoid**
fix podspec to avoid issue with new xcode build system:  …
👎 unable to build node: '.../SwiftRater/SwiftRater.framework/Info.plist' (node is produced by multiple commands;

### CODE REVIEW

**Comment by takecian** [comment]
What is new xcode build system? Which version are you using?

**Comment by krezzoid** [comment]
@takecian the latest one and the "new build system"

**Comment by takecian** [comment]
Oh, I see.
I could reproduced it.

**Comment by takecian** [comment]
@krezzoid thank you for great contribution!!
I have released `1.2.1` now https://cocoapods.org/pods/SwiftRater.

Thank you again :)

**Pull request merged**
